13 Write `Res` struct
restly-rs/restly pull request #16
Opened 2023-06-14 13:27 UTC by gregor-tokarev

1. Add reading from buffer for request
2. Add basic implementation of response struct

2023-06-15 12:11 UTC, alytidae approved these changes

2023-06-19 15:40 UTC, gr3yknigh1 requested changes

2023-06-19 15:46 UTC, gregor-tokarev commented on restless/src/response.rs
> +    pub fn set(&'a mut self, header_key: &'a str, header_value: &'a str) -> &'a mut Res {
express api enforce this

2023-06-19 15:48 UTC, gregor-tokarev commented on restless/src/response.rs
> +    pub fn status(&'a mut self, status: usize) -> &mut Res {
express api enforce this

2023-06-20 05:26 UTC, gr3yknigh1 requested changes
All good. Just remove duplication

2023-06-20 05:26 UTC, gr3yknigh1 commented on restless/src/response.rs
> +        (200, "OK"),
Duplication at 21 line

2023-06-20 05:26 UTC, gr3yknigh1 commented on restless/src/response.rs
> +        (200, "OK"),
same duplication

2023-06-20 10:35 UTC, merged